-- Replace placeholder teams with real 2026 cook team roster + logos
-- Run this in the Supabase SQL Editor.

alter table teams add column if not exists logo_url text;

delete from vote_log;
delete from teams;
alter sequence teams_id_seq restart with 1;

insert into teams (id, name, logo_url, votes) values
  (1, 'Allison Transmission & Stewart & Stevenson', '/team-logos/1-allison-transmission-stewart-stevenson.png', 0),
  (2, 'AMGAS Services (U.S.)', '/team-logos/2-amgas-services-u-s.png', 0),
  (3, 'Archrock', '/team-logos/3-archrock.png', 0),
  (4, 'Atlas Energy Solutions', '/team-logos/4-atlas-energy-solutions.png', 0),
  (5, 'Axis Energy Services', '/team-logos/5-axis-energy-services.png', 0),
  (6, 'Baker Hughes', '/team-logos/6-baker-hughes.png', 0),
  (7, 'Bell Supply Company, LLC', '/team-logos/7-bell-supply-company-llc.png', 0),
  (8, 'BJ Energy Solutions, LLC', '/team-logos/8-bj-energy-solutions-llc.png', 0),
  (9, 'CARBO', '/team-logos/9-carbo.png', 0),
  (10, 'Cardinal Coil Tubing', '/team-logos/10-cardinal-coil-tubing.png', 0),
  (11, 'Charger Services', '/team-logos/11-charger-services.png', 0),
  (12, 'Chevron', '/team-logos/12-chevron.png', 0),
  (13, 'Clean Chemistry, Inc', '/team-logos/13-clean-chemistry-inc.png', 0),
  (14, 'Coastal Chemical', '/team-logos/14-coastal-chemical.png', 0),
  (15, 'ConocoPhillips', '/team-logos/15-conocophillips.png', 0),
  (16, 'Cooper Natural Resources', '/team-logos/16-cooper-natural-resources.png', 0),
  (17, 'Core Laboratories', '/team-logos/17-core-laboratories.png', 0),
  (18, 'Crosscut Gas Partners, LLC', '/team-logos/18-crosscut-gas-partners-llc.png', 0),
  (19, 'Cudd Energy Services', '/team-logos/19-cudd-energy-services.png', 0),
  (20, 'Cummins', '/team-logos/20-cummins.png', 0),
  (21, 'Deep Blue Water', '/team-logos/21-deep-blue-water.png', 0),
  (22, 'DESCH Canada Ltd.', '/team-logos/22-desch-canada-ltd.png', 0),
  (23, 'Devon Energy', '/team-logos/23-devon-energy.png', 0),
  (24, 'Diamondback Energy', '/team-logos/24-diamondback-energy.png', 0),
  (25, 'DNOW Inc.', '/team-logos/25-dnow-inc.png', 0),
  (26, 'Double Eagle', '/team-logos/26-double-eagle.png', 0),
  (27, 'Downhole Chemical Solutions', null, 0),
  (28, 'Dragon Products', '/team-logos/28-dragon-products.png', 0),
  (29, 'EBT Bearings', '/team-logos/29-ebt-bearings.png', 0),
  (30, 'Economy Polymers & Chemicals', '/team-logos/30-economy-polymers-chemicals.png', 0),
  (31, 'Encore Wellhead Systems (Joy Holdings)', '/team-logos/31-encore-wellhead-systems-joy-holdings.png', 0),
  (32, 'Endurance Lift Solutions', null, 0),
  (33, 'Enquest, Deroode, Lockton, Old Smokey, Turtlebox', null, 0),
  (34, 'Enverus', '/team-logos/34-enverus.png', 0),
  (35, 'Explore Group', '/team-logos/35-explore-group.png', 0),
  (36, 'Finoric', '/team-logos/36-finoric.png', 0),
  (37, 'Flotek Industries', '/team-logos/37-flotek-industries.png', 0),
  (38, 'Force Pressure Control', '/team-logos/38-force-pressure-control.png', 0),
  (39, 'GD Energy Products', '/team-logos/39-gd-energy-products.png', 0),
  (40, 'Gilmore Technologies', '/team-logos/40-gilmore-technologies.png', 0),
  (41, 'Gravity', '/team-logos/41-gravity.png', 0),
  (42, 'Gryphon ESP, Butch''s, Transcend Drilling & Permian Equipment Rental', '/team-logos/42-gryphon-esp-butch-s-transcend-drilling-p.png', 0),
  (43, 'H&P', '/team-logos/43-h-p.png', 0),
  (44, 'Halliburton', '/team-logos/44-halliburton.png', 0),
  (45, 'HULK (Oil Tool Solutions)', '/team-logos/45-hulk-oil-tool-solutions.png', 0),
  (46, 'iNet', '/team-logos/46-inet.png', 0),
  (47, 'Innovex', '/team-logos/47-innovex.png', 0),
  (48, 'J&W Services', '/team-logos/48-j-w-services.png', 0),
  (49, 'J4 Oilfield Service (Syndicate Supply)', null, 0),
  (50, 'Key Energy Services, Inc.', '/team-logos/50-key-energy-services-inc.png', 0),
  (51, 'Kodiak Gas Services', '/team-logos/51-kodiak-gas-services.png', 0),
  (52, 'Liberty Energy', '/team-logos/52-liberty-energy.png', 0),
  (53, 'Machinery Auctioneers', '/team-logos/53-machinery-auctioneers.png', 0),
  (54, 'Mako Lift', '/team-logos/54-mako-lift.png', 0),
  (55, 'Maxxim Energy', '/team-logos/55-maxxim-energy.png', 0),
  (56, 'MidCentral, PowerStream, and Expanse', '/team-logos/56-midcentral-powerstream-and-expanse.png', 0),
  (57, 'Mustang Cat/UVL', '/team-logos/57-mustang-cat-uvl.png', 0),
  (58, 'Nabors', '/team-logos/58-nabors.png', 0),
  (59, 'Nomad Proppant Services', '/team-logos/59-nomad-proppant-services.png', 0),
  (60, 'NOV', '/team-logos/60-nov.png', 0),
  (61, 'Oil States International & Thruster Energy', '/team-logos/61-oil-states-international-thruster-energy.png', 0),
  (62, 'Pason', '/team-logos/62-pason.png', 0),
  (63, 'Patterson-UTI', '/team-logos/63-patterson-uti.png', 0),
  (64, 'Permian Resources Operating, LLC', '/team-logos/64-permian-resources-operating-llc.png', 0),
  (65, 'Petro-Hunt, LLC', '/team-logos/65-petro-hunt-llc.png', 0),
  (66, 'Pico Propane / Meritum', '/team-logos/66-pico-propane-meritum.png', 0),
  (67, 'Pintail Completions', '/team-logos/67-pintail-completions.png', 0),
  (68, 'Precision Drilling Corporation', '/team-logos/68-precision-drilling-corporation.png', 0),
  (69, 'Precision Power Cleaning & Primo Field Services', '/team-logos/69-precision-power-cleaning-primo-field-ser.png', 0),
  (70, 'ProPetro/ Silvertip', '/team-logos/70-propetro-silvertip.png', 0),
  (71, 'PureFrac, LLC', '/team-logos/71-purefrac-llc.png', 0),
  (72, 'Ranger Energy Services, LLC', '/team-logos/72-ranger-energy-services-llc.png', 0),
  (73, 'Resource Energy Equipment', '/team-logos/73-resource-energy-equipment.png', 0),
  (74, 'Rig Works', '/team-logos/74-rig-works.png', 0),
  (75, 'RK Supply', '/team-logos/75-rk-supply.png', 0),
  (76, 'SandX', null, 0),
  (77, 'Select Water', '/team-logos/77-select-water.png', 0),
  (78, 'Serva Group', '/team-logos/78-serva-group.png', 0),
  (79, 'SM Energy', '/team-logos/79-sm-energy.png', 0),
  (80, 'Smart Chemical Services', '/team-logos/80-smart-chemical-services.png', 0),
  (81, 'SNF', '/team-logos/81-snf.png', 0),
  (82, 'Spraberry Production Services', '/team-logos/82-spraberry-production-services.png', 0),
  (83, 'TechnipFMC', '/team-logos/83-technipfmc.png', 0),
  (84, 'The E3 Company', null, 0),
  (85, 'The University of Texas Permian Basin', null, 0),
  (86, 'Thomas Oilfield Services, LLC', '/team-logos/86-thomas-oilfield-services-llc.png', 0),
  (87, 'Thru Tubing Solutions & CUDD Pressure Control', '/team-logos/87-thru-tubing-solutions-cudd-pressure-cont.png', 0),
  (88, 'TSI Flow Products', '/team-logos/88-tsi-flow-products.png', 0),
  (89, 'TSS', '/team-logos/89-tss.png', 0),
  (90, 'USA DeBusk', '/team-logos/90-usa-debusk.png', 0),
  (91, 'VoltaGrid Company - Propell', '/team-logos/91-voltagrid-company-propell.png', 0),
  (92, 'VP Sales & Manufacturing', '/team-logos/92-vp-sales-manufacturing.png', 0),
  (93, 'VTX Energy Partners', '/team-logos/93-vtx-energy-partners.png', 0),
  (94, 'Vulcan Industrial', '/team-logos/94-vulcan-industrial.png', 0),
  (95, 'Western Midstream Partners LP', '/team-logos/95-western-midstream-partners-lp.png', 0),
  (96, 'Wildcat Oil Tools', '/team-logos/96-wildcat-oil-tools.png', 0),
  (97, 'WS Energy', '/team-logos/97-ws-energy.png', 0),
  (98, 'Yellow Jacket Oil Tools', '/team-logos/98-yellow-jacket-oil-tools.png', 0),
  (99, 'Caterpillar', null, 0),
  (100, 'FET', null, 0),
  (101, 'Flowco', null, 0),
  (102, 'INNIO Waukesha Gas/Revolution Power Solutions', null, 0),
  (103, 'Iron Oak Energy Solutions', null, 0),
  (104, 'ProFrac Services LLC', null, 0),
  (105, 'SLB', null, 0),
  (106, 'Target Hospitality', null, 0),
  (107, 'Taylor Machine Works', null, 0),
  (108, 'Edge OFS', null, 0),
  (109, 'SandPile', null, 0);

select setval(pg_get_serial_sequence('teams', 'id'), (select max(id) from teams));